animals = ("cat", "dog", "giraffe", "lion", "elephant", "badger")

print(animals[2])
print(animals[1:4])
print(animals[-1])
print(animals[-4:-1])
print(animals[1:-1:2])
print(animals[:3])
print(animals[::2])
print(animals[::])